ALTER TABLE `rfdb2`.`tblMoney` 
ADD COLUMN `aid` INT NULL DEFAULT NULL AFTER `date`,
CHANGE COLUMN `income` `income` DECIMAL(11,2) NULL DEFAULT NULL AFTER `aid`,
CHANGE COLUMN `fixed` `fixed` DECIMAL(11,2) NULL DEFAULT NULL AFTER `income`,
CHANGE COLUMN `costs` `other` DECIMAL(11,2) NULL DEFAULT NULL ,
CHANGE COLUMN `id_frm` `bid` INT NULL DEFAULT NULL , RENAME TO  `rfdb2`.`tbl_finances` ;
